# title: FPGA Maze Solver
# description: Building a wall-following maze solver on an FPGA — PWM, sensors, FSM, and everything in between.
# theme: jekyll-theme-cayman

# markdown: kramdown
# highlighter: rouge

# nav:
#   - title: Home
#     url: /docs/
#   - title: PWM Generation
#     url: /docs/pwm
#   - title: Sensors
#     url: /docs/sensors
#   - title: FSM
#     url: /docs/fsm
#   - title: Results
#     url: /docs/results


title: Mazesolver bot in FPGA
description: Building a wall-following maze solver on an FPGA — PWM, sensors, FSM, and everything in between.
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

# Theme settings
color_scheme: dark   # or remove this line for light mode
custom_css: assets/css/custom.css

url: https://asmitaa16.github.io
baseurl: /mazesolver_fpga

footer_content: "Maintained by <a href='https://github.com/asmitaa16'>asmitaa16</a> & <a href='https://github.com/SiriusB07'>SiriusB07</a>. Hosted on GitHub Pages."

